# promo-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: promo
spec:
  replicas: 5
  selector:
    matchLabels:
      app: promo
  template:
    metadata:
      labels:
        app: promo
    spec:
      containers:
      - name: promo
        image: python:3.9
        command: ["python", "-m", "http.server", "5001"]
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: promo
spec:
  type: LoadBalancer
  selector:
    app: promo
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
