apiVersion: v1
kind: Service
metadata:
  name: sales
spec:
  selector:
    app: sales
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sales
  template:
    metadata:
      labels:
        app: sales
    spec:
      containers:
        - name: sales
          image: curlimages/curl:7.85.0
          command: ["sh", "-c", "until curl promo:5000; do echo waiting for promo; sleep 2; done; echo promo is up; sleep 3600"]
          ports:
            - containerPort: 5001
